apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: sample-app
    namespace: argocd
spec:
  project: argocd-sample
  source:
    repoURL: https://github.com/YutangShi/test-argocd.git
    targetRevision: HEAD
    path: apps/
    helm:
      valueFiles:
        - values.yaml
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
#      syncOptions:
#        - CreateNamespace=true
      automated:
        prune: true
        selfHeal: true
