apiVersion: v1
kind: Namespace
metadata:
  name: argo-demo

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo-nginx
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`argo-nginx.allenshi.com`)
      kind: Rule
      services:
        - name: nginx
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: argo-demo
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: argo-demo
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: http
            containerPort: 80
